name: Publish to npm

on:
  push:
    branches:
      - main # Use the main branch for publishing; adjust to 'master' or 'develop' if needed

jobs:
  publish:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner for compatibility

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 # Checks out the repository code

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18" # Specify Node.js version; adjust if your project requires a different version
          registry-url: "https://registry.npmjs.org" # npm registry for publishing
          cache: "npm" # Cache npm dependencies to speed up builds

      - name: Install Dependencies
        run: npm ci # Installs dependencies cleanly using package-lock.json

      - name: Run Tests
        run: npm test # Runs tests to ensure the package is stable before publishing
        continue-on-error: false # Stop the workflow if tests fail

      - name: Bump Version
        run: npm version patch # or 'minor'/'major' depending on your versioning strategy

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # Uses the npm token stored in GitHub Secrets
        run: npm publish --access public # Publishes package as public; remove --access public for private packages
