name: Publish Package to npmjs

on:
  push:
    branches:
      - main
# on:
#   release:
#     types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
      - run: npm ci
      - run: npm test

      - name: Publish to npm
        run: npm publish --access public --otp=${{ secrets.NPM_OTP }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
