name: Publish to npm

on:
  push:
    branches:
      - main # Use the main branch for publishing; adjust to 'master' or 'develop' if needed

jobs:
  publish:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner for compatibility

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 # Checks out the repository code
        with:
          fetch-depth: 0 # Required for Git history access when bumping version

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18" # Specify Node.js version; adjust if needed
          registry-url: "https://registry.npmjs.org" # npm registry for publishing
          cache: "npm" # Cache npm dependencies to speed up builds

      - name: Install Dependencies
        run: npm ci # Installs dependencies cleanly using package-lock.json

      - name: Run Tests
        run: npm test # Runs tests to ensure the package is stable before publishing
        continue-on-error: false # Stop the workflow if tests fail

      - name: Configurar git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Bump Version
        run: npm version patch # Increments the patch version and creates a Git commit
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # Ensure npm token is available

      - name: Push Version Update
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }} # Use the Personal Access Token stored in Secrets
        run: |
          git push https://$GITHUB_TOKEN@github.com/Raicamposs/toolkit.git --tags
        # Pushes the version bump commit and tag using the PAT for authentication

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # Uses the npm token stored in GitHub Secrets
        run: npm publish --access public # Publishes package as public; remove --access public for private packages
